version: '3'
services:
  nginx:
    image: lxshpk/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      HTTPS_DOMAINS: |
        example.com
        sub.example.com
      HTTP_DOMAINS: |
        sub2.example.com
      CERTBOT_EMAIL: mail@example.com
      CERTBOT_ARGS: --dry-run
    volumes:
      - "/var/lib/letsencrypt:/var/lib/letsencrypt"
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "./upstreams.conf:/etc/nginx/conf.d/upstreams.conf"