version: '3'
services:
  nginx:
    image: lxshpk/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      NGINX_PROXY_PASS: |
        http://example.com -> http://service:8080
        https://sub.example.com -> http://service:8081
        http://external.example.com -> http://external.com

      CERTBOT_EMAIL: mail@example.com
      CERTBOT_ARGS: --dry-run
